### ISSUE TITLE
conflict: node version doesn't fit the latest eslint

### ISSUE THREAD

**Issue by Sotyoyo** [oPauloChaves/koa-mongo-api-starter#4]
when i run it with 'docker-compose build --force-rm'

terminal shows

error eslint@5.16.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".

i fix the first line in Dockerfile to 'FROM node:8.15'

then it works!

Such a nice project! thank you for sharing.

**Comment by oPauloChaves** [comment]
Good catch @Sotyoyo!
I have udpated node version on `Dockerfile` and also made some improvents.
I'm glad you like this boilerplate.
